#+TITLE: Bruno Cuconato

#+begin_export html
<a href="#publications" style="font-style:italic;font-size:0.8em;">[skip to publications]​</a>
#+end_export

I recently defended my PhD thesis at the computer science department
at [[https://en.wikipedia.org/wiki/Pontifical_Catholic_University_of_Rio_de_Janeiro][PUC-Rio]], under the supervision of [[https://www-di.inf.puc-rio.br/~hermann/][Edward Hermann Haeusler]]. The text
of my thesis will be available soon at PUC's [[https://www.dbd.puc-rio.br/][library]] (I will add a
link to it in this page too).

During my PhD I mostly worked on the Labelled Logical Framework, a
[[https://en.wikipedia.org/wiki/Logical_framework][logical framework]] with a simple meta-language intended to facilitate
the implementation and use (see the [[https://glf.tecmf.inf.puc-rio.br/][web interface]]) of deductive
systems. This is in opposition to most logical frameworks (or proof
assistants, as they like to be called) these days, whose focus lies
more in the verification of the systems' properties.

Previously I have worked with natural language processing, with a
focus in developing datasets (under the guidance of [[https://arademaker.github.io/][Alexandre
Rademaker]]). For my master's thesis, I have developed a [[./blog/gf-grammars.org][digital grammar
for Portuguese]] under the Grammatical Framework formalism.

You can find my contact information in any of the papers below.

** Publications
   :PROPERTIES:
   :CUSTOM_ID: publications
   :END:

  - Haeusler, E.H., /Bruno Cuconato/, Luiz A. Glatzl, Maria L.
    Guateque, Diogo M. Vieira, Elvismary M. de Armas, Fernanda Baião,
    Marcos Catanho, Antonio B. de Miranda & Sergio Lifschitz.
    *Intentional Semantics for Molecular Biology* (BSB 2023, full
    paper). In: Reis, M.S., de Melo-Minardi, R.C. (eds) Advances in
    Bioinformatics and Computational Biology. BSB 2023. Lecture Notes
    in Computer Science, vol 13954. Springer, Cham.
    https://doi.org/10.1007/978-3-031-42715-2_9
    {{{publication(haeusler-intentional-bsb)}}}
  - /Bruno Cuconato/, Jefferson de Barros Santos, Edward Hermann
    Haeusler. *A graph logical framework* (EBL XX 2022, presentation-only)
  - /Bruno Cuconato/, Jefferson de Barros Santos, Edward Hermann
    Haeusler. *A logical framework with a graph meta-language* (LFMTP
    2021, presentation-only)
    {{{publication(cuconato2021-logical-framework-lfmtp)}}}
  - /Bruno Cuconato Claro/. *A computational grammar for
    Portuguese*. MSc Thesis at EMAp/FGV, advised by Alexandre
    Rademaker (2019)
    {{{publication(cuconato2019-computational-grammar-fgv)}}}
  - Alexandre Rademaker, /Bruno Cuconato/, Alessandra Cid, Alexandre
    Tessarollo, Henrique Muniz. *Completing the Princeton Annotated
    Gloss Corpus Project* (GWC 2019)
    {{{publication(rademaker2019-glosstag-gwc)}}}
  - Leonel Figueiredo de Alencar, /Bruno Cuconato/, Alexandre
    Rademaker. *MorphoBR: An Open Source Large-Coverage Full-Form
    Lexicon for Morphological Analysis of Portuguese* (Texto
    Livre 2018) {{{publication(alencar2018-morphobr-textolivre)}}}
  - /Bruno Cuconato/, Alexandre Rademaker. *A computational grammar
    for Portuguese* (PROPOR 2018, demo)
    {{{publication(cuconato2018-grammar-propor)}}}
  - Alexandre Rademaker, Fabricio Chalub, /Bruno Cuconato/, Henrique
    Muniz, Guilherme Passos. *CL-CONLLU Universal Dependencies in
    Common Lisp*. (PROPOR 2018, demo)
    {{{publication(rademaker2018-conllu-propor)}}}
  - Suemi Higuchi, Cláudia Freitas, /Bruno Cuconato/ and Alexandre
    Rademaker. *Text Mining for History: first steps on building a
    large dataset* (LREC 2018)
    {{{publication(higuchi2018-dhbb-lrec)}}}
  - Alessandra Cid, Alexandre Rademaker, /Bruno Cuconato/, Valeria de
    Paiva. *Linguistic Legal Concept Extraction in Portuguese*
    (JURIX 2018) {{{publication(cid2018-legal-concept-jurix)}}}
  - Pedro Delfino, /Bruno Cuconato/, Guilherme Paulino Passos, Gerson
    Zaverucha, Alexandre Rademaker. *Using OpenWordnet-PT for Question
    Answering on Legal Domain* (GWC 2018)
    {{{publication(delfino2018-oab-gwc)}}}
  - Pedro Delfino, /Bruno Cuconato/, Edward Hermann Haeusler,
    Alexandre Rademaker. *Passing the Brazilian OAB Exam: Data
    Preparation and Some Experiments* (JURIX 2017)
    {{{publication(delfino2017-oab-jurix)}}}
