#+TITLE: Borboletas e preconceito no século XIX
#+DATE: <2017-02-10 Sex>
#+DESCRIPTION: Sobre a vida e a obra de Margaret Fountaine.
#+KEYWORDS: literature art
#+LANGUAGE: pt

acabei de ler um livro. um diário. na verdade, pedaços de um
diário. do diário de margaret fountaine, vendido sob o inócuo título
de =love among the butterflies=. fountaine foi uma moça nascida numa
família que se achava respeitável (i.e., genealogia traçável até o
século xv). respeitabilidade não significava dinheiro de sobra, mas
tinham o que precisavam pra manter a respeitabilidade (ter familiares
ricos ajudava). fountaine aprendeu tudo que uma menina vitoriana
deveria aprender, especialmente a defender sua respeitabilidade com
unhas e dentes usando protocolos de comportamento tradicionais nunca
questionados e que pareciam sempre cercear sua liberdade.

mas a liberdade sempre chamou fountaine mais forte.

um dia um parente rico morreu e deixou pra fountaine, pra suas irmães
e pra sua mãe uma considerável soma de dinheiro, que aplicada de
maneira confiável por um tio rico, rendia a fountaine uma renda mensal
(um salário pelo cargo de ter tido a sorte de familiares ex-ricos
mortos). a renda não era suficiente para uma vida de luxos, mas
permitia que fountaine viajasse o quanto quisesse, sem precisar de
trabalhar.

/saudades desse tempo?/

/1. a probabilidade de você, se nascido na época, ser uma pessoa com
a/ /sorte de fountaine e não um trabalhador de baixa renda sem
direitos trabalhistas seria bem pequena/

/2. boas(?) notícias, talvez estejamos voltando pra essa época [[http://www.economist.com/blogs/buttonwood/2014/03/demography-and-inequality][ao
menos nesse aspecto]]./

como não existem revoluções (no sentido de mudanças abruptas,)
fountaine começou a aproveitar a vida viajando por diferentes cidades
do reino unido, exercitando seu hobby de desenhar catedrais.

*

por muito tempo sua catedral favorita foi a de sua cidade natal. era
lá que ela às vezes avistava um corista irlandês pelo qual ela se
apaixonou. transbordando de romantismo, fountaine se atraía pelo moço
ao mesmo tempo em que se reprimia por ele ser de uma classe mais baixa
(i.e., indigno dela). mesmo assim, a liberdade econômica de que
desfrutava lhe permitia uma liberdade maior em vários
sentidos. escrevia cartas nas quais sabia estar infringindo as
convenções sociais de seu tempo. fountaine chegou a visitá-lo em sua
terra natal, ficando sozinha num hotel (algo incomum na época) e
conhecendo a família. chegaram a virar noivos, ao que o tio rico
comentou de maneira fria:

#+BEGIN_QUOTE
  "i am only sorry that it is by your late uncle's money that you gave
  been able to carry out what i cannot but call a most unfortunate
  engagement."
#+END_QUOTE

/conta em favor do tio rico que ele poderia ter cancelado a renda
mensal de fountaine enquanto gestor da herança, mas não o
fez. efetivamente nos impediu de averiguar se fountaine era [[https://odanoburu.github.io/2014/09/10/julieta-&-romeu&-58;-uma-hist%C3%B3ria-utilitarista.html][uma
romântica à la julieta & romeu]]/

depois de algumas reviravoltas e de cartas melosas, o noivado foi
cancelado, e fountaine se sentia aliviada sempre que ouvia notícias
das bebedeiras e dívidas de jogatina do seu primeiro quase-marido.

/o que talvez nunca tenha ocorrido a fountaine é que seu ex-noivo só
tenha se dado a beber porque teve a suposta decência de abrir mão de
um casamento que supostamente nunca daria certo por ele ser de uma
classe inferior e por ele não ter muito dinheiro. seu objetivo talvez
tenha sido salvar fountaine de uma decisão que a sociedade a que
pertenciam considerava errada, sacrificando a própria felicidade por
isso. isso é tudo especulação minha, claro. mas acho possível./

*

a cada viagem fountaine ía mais longe. aprendeu a andar de bicicleta e
viajou o sul da frança. teve aulas de canto em milão. em certo momento,
abandonou os desenhos de igreja e o canto, e passou a ter o hobby único
de caçar borboletas. nas suas noites em alojamentos no estrangeiro,
fountaine se divertia recebendo as atenções de diversos homens, só pra
depois rejeitá-los da forma que foi rejeitada por seu primeiro amor.

fountaine foi envelhecendo, mais familiares foram morrendo, e
fountaine fazia cada vez mais o que queria. a impressão que tenho é de
que uma voz no fundo da cabeça de fountaine falava, sempre que ela
estava se divertindo:

#+BEGIN_QUOTE
  você, mulher respeitável, não deveria estar sozinha nessa montanha
  na itália caçando borboletas sozinha, mas sim casada com um homem
  rico e respeitável.
#+END_QUOTE

ou então,

#+BEGIN_QUOTE
  você, mulher respeitável, não deveria estar com esse bando de homens
  caçando borboletas numa floresta num país distante
#+END_QUOTE

ou ainda,

#+BEGIN_QUOTE
  você, mulher respeitável, não deveria estar atravessando uma serra
  assolada por bandidos tendo dois homens
  não-ocidentais-e-portanto-inferiores-e-indignos-de-confiança como
  seus guias até a próxima cidade, onde você vai ficar num quarto de
  uma casa de barro cheio de pulgas. o seu lugar é numa mansão quente
  e confortável nos campos ingleses, cheio de crianças e de um marido.
#+END_QUOTE

mas fountaine sempre ignorava essa voz. afinal, ela adorava viajar e
caçar borboletas, e odiava ficar em casa na inglaterra.

*

viajando pelo que na época ainda era o império otomano, fountaine
empregava como guia um certo khalil. khalil nunca escondeu seu amor
por ela. fountaine inicialmente achava que khalil era só mais um dos
muitos assediadores que já havia encontrado, mas um menos perigoso e
mais obsequioso do que a maioria (e que além disso falava um bom
inglês).  passou a empregar khalil em várias outras viagens por países
da região, e vendo que o amor de khalil não diminuía, prometeu casar
com ele.

*logo ele.* khalil. um *sírio*, ainda que cristão. considerado de raça
e de classe inferiores. e além disso tudo, pobre, pobre, *pobre*.

mas a sociedade que fountaine tinha sido criada pra agradar tinha cada
vez menos peso nas suas decisões.

antes que não tivesse importância alguma, no entanto, fountaine
recebeu uma carta. a carta era da irmã de um vice-cônsul
britânico. fountaine havia conhecido o vice-cônsul e a irmã numa de
suas viagens, e não tinha mais pensado nos dois desde então. a irmã
perguntava se ela ainda estava solteira (ainda, pois mesmo que
houvesse muitas mulheres que escolhiam nunca se casar, essa ainda era
uma escolha impensável). dizia que o irmão precisava se casar pois não
tinha a renda exigida pelo seu cargo, e que ela preferia que o irmão
se casasse com uma mulher inglesa e não com a francesa de renda anual
de mil libras/ano que estava no papo dele.  a irmã perguntava se
fountaine estaria interessada e o quanto era sua renda.

/sim, amigues, isso acontecia no nosso querido século xix./

fountaine respondeu dizendo que sua renda mal ultrapassava
quatrocentas libras/ano, e que tinha se decidido há muito não se
casar. quando o irmão-vice-cônsul em pessoa lhe escreveu, fountaine
disse que já tinha viajado demais pra conseguir se instalar num lugar
só, que seria pra sempre infeliz caso o fizesse, e que seria uma
péssima esposa. na ausência de um não enfático, o irmão-vice-cônsul
lhe respondeu com sonhos e planos despedaçados pela decisão de
fountaine.

sem receber cartas de khalil há uns dias (os correios ingleses eram
impressionantemente eficientes; os do império otomano, bem menos), e
lisonjeada por ser uma quarentona solteira cortejada por dois homens
(nas palavras, quase que literalmente), e ainda que decidida por dizer
não, fountaine respondeu o vice-cônsul de maneira "mais encorajadora",
e até lhe enviou uma foto. fountaine achava que escolher khalil seria
idiota, mas ela estava decidida a fazê-lo, idiotice ou não.

ao mesmo tempo, nota o editor do diário-livro, ficar temporadas com a
sua mãe na inglaterra era chato, e a vida com o vice-cônsul seria uma
boa maneira de fugir isso. ficar com o vice-cônsul seria enganar a ele
e a khalil, pois já havia se prometido pra khalil, e porque o
vice-cônsul jamais ficaria com ela se soubesse "metade da verdade
sobre ela". ainda assim, fountaine se diz, muitos homens resolvem se
casar e levar uma vida tranquila depois de viverem de maneira
/selvagem/, sem escrúpulo algum, então porque ela não deveria fazer o
mesmo?

aparentemente contra seus desejos verdadeiros, fountaine escreve em
seu diário que estava

#+BEGIN_QUOTE
  quite inclining to lead towards the course of action which would
  lead me to find myself a 'respectable married woman', after all.
#+END_QUOTE

quando aceita um noivado secreto, ela se pergunta:

#+BEGIN_QUOTE
  why should i sacrifice liberty for the sake of appearing to
  advantage before the world? my world is the deserts of torrid lands
  where wandering tribes sit round their camp fires at night; my world
  is in the mountain forests...
#+END_QUOTE

*

o que o diário de fountaine me faz pensar é no quão influentes são os
preconceitos de nossas épocas, mesmo que sejamos, como fountaine,
pessoas que tentem (e consigam, em certa medida) superá-los.

*

eu conheci esse livro em uma aula sobre literatura de viagem, que me
apresentou pérolas como chaucer (pai da literatura inglesa, junto com
shakespeare) e chatwin. por causa de um desafio que estava rolando em
2014, me decidi a ler mais autoras (a maior parte do que lemos é
escrito por homens, embora talvez a gente não pare pra pensar
nisso). além da fountaine, também li [[https://archive.org/details/bydesertwaystoba00wilkrich][louisa jebb]], outra escritora
corajosa que viajou pelo oriente médio de domínio otomano. (leiam, ela
é sensacional. e engraçada).
