#+TITLE: On hope
#+DATE: <2022-05-10 Tue>
#+DESCRIPTION:
#+KEYWORDS: reflections
#+LANGUAGE: en

Picture something about the world that made you sad or revolted
recently.

(I'm sure you can think of plenty of examples.)

If you're anything like me, it's not just the event itself that
bothers you, but also the fact that it shouldn't have happened at
all. I mean the kind of event that has already happened several times
in history (maybe in slightly different forms), and given the benefit
of hindsight, that we humans should have been past that already.

I can tell myself that maybe people do realise the problem with what
they are doing, but they feel they are being forced into that course
of action regardless, but that's not what I want to talk about. What I
want to talk about is about avoiding hopelessness.

(It is my impression that this has been increasingly difficult lately,
but that's a very subjective view.)


# We forgive our forefathers (ok, not always) because they didn't know
# better; conversely, we judge our contemporaries harshly, because
# they should know better. ~We've had people bathing in the king's
# blood (thinking it sacred) after Louis XVI was beheaded in the
# French revolution,~ (couldn't find a reference for this, but we
# could use women's rights being ignored for so long as an example
# too) but we've also had bartolomeo de las casas defending native
# people's humanity in 1492. Today is the same, there's all sorts of
# behaviours we find offensively backward, but there's also the kind
# of trailblazing behaviour that for now is rare, but hopefully will
# be more and more common in the future.

# https://reasonstobecheerful.world/
