#+TITLE: #StreetArt
#+DATE: <2014-10-12 Dom>

in brazil we have a consensus regarding street art.

street art can be of two (and only two !) types. it can be either
‘good’, and is thus denominated ‘graffiti’, or it can be ‘bad’, being
called ‘pixação’. (‘pixação’ is basically writing names [‘tagging’] or
what are deemed unreadable signs, e.g.  [[http://www.fatcap.com/graffiti-style/wildstyle-1/pictures.html][wildstyle]].  anything that does
not carry an obvious meaning is considered artless: a mere ‘pixação’.

this categorization reminds me of yet another presupposed dualism: in
brazil, a transgender woman can be either a ‘transsexual’ or a
‘travesti’ (‘transvestite’). ‘transsexual’ is a word that shows a
degree of acceptance by society; the person in question could pretend
to be cisgender and "few would notice otherwise". a transgender
person, when seen as a ‘travesti’, is usually someone forced to the
margins of society for not conforming to gender norms. (if you can
read portuguese, don't bother reading what i wrote here, go read [[http://www.oestigmatrans.org/qual-e-a-diferenca-entre-a-travesti-e-a-transexual/][what
Sofia has to say]]!)

this is yet another instance where a dualism fails to grasp the
complexity of a situation.

in the film ‘cidade cinza’ (‘grey city’; trailer w/ english subs [[https://www.youtube.com/watch?v=7NpppZaGfJo][here]])
we watch two employees working for the são paulo city government
[[https://www.youtube.com/watch?v=jumIQ47TQPo][debating which street art pieces are art and which are not]]. their work
is to clean the city from the so-called ‘pixação’. (‘graffiti’, as the
film shows, is being increasingly tolerated by authorities due to the
artists' struggle for respect.) the street art pieces which are ruled
out as unworthy are [[http://youtu.be/LZsxPBWuH8k?t=23s][greyened out]].

i remember not liking how the film portrays the scene. i remember
having the impression that the employees' comments regarding street
art were led to be seen as ridiculous (as they are) because the
employees are not art historians or art critics, and not because
trying to define art is pointless in itself.

os gêmeos (a famous graffiti duo), having noticed the failure of the
dualism graffiti x ‘pixação’, decided to play along with it.

as the good artists that they are (and more importantly in this case,
as the good artists that they are generally /recognised/ to be,) they
decided to paint [[http://www.fatcap.com/graffiti/12928-os-gemeos-barcelona.html][this]].  (okay, actually something very similar to
that, as the one in question is in são paulo and the one i linked to
is in barcelona. i couldn't find the image of right one).

an art critic that tried to differentiate between graffiti and
‘pixação’ would break down in aporia upon the sight of this work. if
name-writing is mere ‘pixação’, why would a name-writing by os gêmeos,
as good as they may be (and are,) be any different? with this graffiti
(and several others, in fact), os gêmeos were trying to demonstrate
that *anyone* can leave their mark on the city, that *anyone* can make
art, and that *no-one* should be ruling over what is art and what is
not.

the city government of são paulo employees, though, simply said they
would leave the "pretty" boy figure alone, [[https://www.youtube.com/watch?v=LZsxPBWuH8k][and greyened the rest out]].
