#+TITLE: (my) guide to Rio de Janeiro
#+DATE: 2021-11-30
#+OPTIONS: toc:2

São Sebastião do Rio de Janeiro is a city full of beautiful sights,
and historical and cultural landmarks. (The food could be better,
though — for that you'll have to visit São Paulo, Minas Gerais, or
Bahia.)

Here I collect a list of my favorite spots, divided by category, and
with a few comments on each. You should probably search for more
details and up-to-date instructions if you actually plan to visit any
of them (feel free to contact me for help if you wish).

This is a work-in-progress, and feedback is welcome. I should add some
pictures and maps, but for now this is text-only (suggesting suitable
pictures with compatible licenses would be a great contribution).

** Geography
   The city of Rio is delimited by the mountains and the sea
   (Guanabara bay to the East, Sepetiba bay on the far West, and the
   Atlantic ocean to the South). It boasts three major forested and
   mountainous areas with peaks in the 1000m range, to West (Pedra
   Branca State Park, Pedra Branca range), North (Gericinó Municipal
   Park, Gericinó range) and the Southeast (Tijuca National Park,
   Tijuca range). The city grew from what is today the city center
   (/Centro/), right next to the easily defensible (because of its
   narrow mouth) Guanabara bay, to all the directions it could
   manage. Most forest (like in the rest of the Brazilian Southeast
   region) that was not in mountainous areas was cut down, swamps were
   drained, and rivers were diverted, wrapped in cement or paved over
   (not to mention blemished with human waste). Homes and churches and
   roads were built, and the result is the city we have to today.

   People subdivide the city and its inhabitants (the /cariocas/) more
   or less like so: the city center (/Centro/), in which few people
   live but many commute to, the Zona Sul (South side), where the
   nicer neighbourhoods traditionally are in, and many of the famous
   beaches are too (think Copacabana, Ipanema, etc.), Tijuca (where
   the /tijucanos/ live) and its satellite neighbourhoods of Grajaú,
   Andaraí, etc., the Zona Norte, where several different
   neighbourhoods lying to the North are lumped together as one, Barra
   da Tijuca, or most often just Barra (where the /barrenses/ live)
   and its satellite neighbourhoods of Recreio, Jacarepaguá, etc., and
   (finally) the Zona Oeste, where again several different
   neighbourhoods (this time lying to the Northwest and West) are
   lumped together. Do note that technically Barra would be a part of
   Zona Oeste and Tijuca would be a part of Zona Norte, but they are
   regional centers that deserve special denomination.

*** Beyond Rio
    The city of Rio is the capital of the Rio de Janeiro State, which
    has many other places of interest, some of them not too far from
    Rio (the city), at least for Brazilian standards (definitely not
    by usual European standards). In this guide we will mention and
    sometimes talk about these other places, but I'll also mention the
    highlights here.

    Right next to Rio, to the other side of Guanabara Bay, you have
    Niterói. Most well-known for its beautiful views of Rio (like the
    ones you get in /Parque da Cidade/ — not to be confused with Rio's
    /Parque da Cidade/), Niterói has quite a few nice spots of its
    own, but is totally outside the regular touristic route.

    To the North of Rio you have the Serra dos Órgãos National Park,
    which has beautiful mountains and forests (you could think of
    Rio's mountains and forests as a microscopic version of these, with
    more degradation but also the greater convenience of it being
    right there in the middle of the city). In this region you find
    the cities of Petrópolis (which might be worth the visit if you'd
    like to know more about Brazil's imperial history), Teresópolis
    and Nova Friburgo, which are all have their share of pretty
    neighbourhoods and beautiful landscape, and is where cariocas go
    if they want to feel cold (or maybe just less warmth). Going a bit
    further West, next to the border to São Paulo, you have the
    Itatiaia National Park, which has some of the highest peaks of
    Brazil. In fact Pico das Agulhas Negras was thought to be the
    highest point of Brazil up until the 1960s, given how remote the
    actual high point is (Pico da Bandeira) and how rudimentary
    altitude measurements were back then. In Itatiaia you can find not
    only rain forests, but also a very different type of vegetation,
    that typical of high altitude tropical climates (you can also find
    this type of vegetation at the nearby Bocaina National Park, which
    I also recommend!).

    Despite Rio having plenty of beaches, cariocas still like to
    travel to other beaches nearby. Some cariocas are even partial to
    the Blue coast's (/Costa Azul/) cities of Búzios, Arraial do Cabo
    and Cabo Frio or to the Green coast's (/Costa Verde/) cities of
    Mangaratiba, Angra dos Reis and Paraty. The later region also has
    great waterfalls and beautiful mountains, not to mention a
    multitude of islands (maybe you can guess on whose coast's side
    the writer is on).

** Transportation
   :PROPERTIES:
   :CUSTOM_ID: rio-transport
   :END:
   Unlike other big cities like São Paulo or London, Rio did not grow
   radially — there were mountains and the bay and the sea in the
   way. Geography played a role in the cities development too; places
   like Barra which were basically dunes and wetlands were settled way
   later than Jacarépaguá and Santa Cruz (the latter being way farther
   from the city center but more easily accessible). All this means
   that Rio's layout is a bit weird, and there are some places that
   are not so far as the crow flies but are quite far as the bus goes.

   Rio's best transportation mode overall is the metro: it is not too
   expensive, it is safe, and it is quite fast and reliable. Cars can
   be fast, but traffic jams in Rio may occur at any time, so if you
   have to be somewhere at a strict time do leave early. Don't worry
   about arriving late for a meetup or meeting — if it's not a job
   interview (and sometimes even then) when a time is set it is never
   a point in time but a range extending 1 or 2 hours after the point
   it begins.  The metro is very limited, however; it has (supposedly)
   3 lines, but they behave more like 1.5 lines. You can go from the
   Northeast of the city (Zona Norte) or Tijuca to Barra and back,
   going through the downtown and most of Zona Sul (the metro more or
   less follows the coastline there, so it misses neighbourhoods like
   Santa Teresa, Laranjeiras, and Gávea).

   Buses are the lifeblood of the cities public transportation, and
   are the mode that will take you anywhere. If you come from
   somewhere with a decent transportation system, beware: Rio's buses
   don't operate on a strict schedule, which would be impossible with
   the uncertain nature of traffic in the city. Nor can they be
   geolocated through official means, which could save you from
   waiting too long at a bus stop (it is not rare for you to wait for
   almost 30 minutes and then have two or three buses of the same line
   going the same way appear, all crowded). You might have some
   precision from a transportation app like Moovit (not officially
   sanctioned), which may get geolocation information from users and
   report bus locations back to other users.

   A note about the ticketing: there's no full day pass that can be
   used across all transportation modes, and the bus and metro systems
   are generally separated, so a ticket from one will not work on the
   other. There are transportation cards that give a semblance of
   integration (like letting you take two buses in the same two hour
   frame) or getting you a discount on the metro ticket if you're
   coming from a bus, so if these interest you do search for them on
   the web.

   Generally what you want to do is use the metro whenever possible,
   complementing it with ride sharing apps like Uber (assuming that
   fits on your budget) and maybe sometimes taking buses and other
   modes (Rio has trams in the city center, and boats taking you to
   Niterói and Ilha de Paquetá) if they are convenient enough to get
   to your destination. Rio also has plenty of taxis, but the writer
   prefers the ride sharing apps for their convenience (no need to
   hail a random car on the street) and their predictability (you are
   fairly certain of the price before the start of trip). Some taxi
   apps exist that should emulate fairly well the ride-sharing app
   experience, but the writer can't personally recommend any.


** Nature
   Rio has a wet tropical climate which hovers around the 20s degrees
   Celsius in the winter and around the 30s in the summer, so you can
   conceivably do any of the activities described below all year
   round. If you are going outdoors I'd say the winter is definitely
   The best season because the temperatures are more comfortable and
   it doesn't rain as much. In the summer it is more likely to rain
   (although usually only in the afternoon, and even then it's not
   every day like in the Brazilian equatorial regions), and you are
   certain to sweat, but at this point you are used to the sweat and
   because it's warm the rain doesn't bother as much as it might
   bother you in the winter.

   Because the sea in Rio is cold, you probably don't want to go to
   the beach on a cold winter day, but for me the sunny/warm winter
   days are the best. In the summer heat the beach is one of the best
   places to be, you have minimal clothes on (or none if you're the
   Abricó beach), the sea breeze is really refreshing, and the sea is
   cold and cools you right up (the more North you go in the Brazilian
   coast the warmer the sea gets, which is good for winter
   beach-going, but not so good for summer beach-going).

*** Pedra Bonita
    :PROPERTIES:
    :CUSTOM_ID: pedra-bonita
    :END:

    The Rio hike with one of the best cost-benefit ratio (another
    contender is [[#morro-da-urca][Morro da Urca]]). Easy to follow, short, and with a
    beautiful view of [[#pedra-da-gavea][Pedra da Gávea]], São Conrado, Barra da Tijuca,
    and a part of Zona Sul.

*** Morro da Urca
    :PROPERTIES:
    :CUSTOM_ID: morro-da-urca
    :END:

    Most people recognize the sight of Morro da Urca, although many
    would only know the name of its taller sibling the Pão de
    Açúcar. You can of course take the famous /bondinho/ (cable car)
    to access both, but if you don't really fancy paying a
    disproportionate amount for it, you can hike up the Morro da Urca
    for free (or climb the Pão de Açúcar if you have the ability and
    equipment). If you can make it on a weekday you can even hike up
    before the sunset and go down for free on the cable car after the
    trail closes at 18:00 (on the weekend they'll make you pay for the
    descent). The view is of course beautiful, one of the most
    well-known sights of Rio. It's even nicer from the Pão de Açúcar
    though, so you'll have to decide if the cost is worth it or not
    (there are a lot of other and taller mountains in Rio, but the
    view from Pão de Açúcar is very unique because you can see the
    city from one of its corners).

*** Pedra da Gávea
    :PROPERTIES:
    :CUSTOM_ID: pedra-da-gavea
    :END:
    Pedra da Gávea is the most challenging of Rio's regular hike menu
    (you can of course request the maître for a special treat from the
    chef). Standing at roughly 850m tall and really close to the sea,
    you get a great view from the western-most regions of Rio (up
    until the Pedra Branca State Park mountains prevent you from
    seeing more), the Tijuca National Park and its beautiful mountains
    (of which Gávea is but one), and Zona Sul.

    You'll have to face the infamous /carrasqueira/, which is a
    climbing section that looks scary enough for a beginner but which
    is not too bad really, and you can always get help (in the form of
    rope and other equipment) from the climbing professionals there
    for a certain amount of money. Do note that you can do this part
    without any equipment, but you do so at your own risk (as a sign
    there warns you); it has a beautiful view of Itanhangá (the
    neighbourhood just below it), so you can always pause the climb at
    one of several sweet spots for a refreshment of your eyes. I've
    seen children and seniors climbing it with no equipment, so if you
    can handle your nerves, follow instructions (don't be afraid to
    ask for help, everyone is nice), and are moderately in shape, you
    can probably do it too.

    Once at the top you get to a large rock face which you can
    explore, there are many different angles (and photo opportunities
    if you are into this sort of thing). If you have the time make
    sure to visit both the part overlooking the sea and the ‘back’
    part overlooking the forested mountains. You might be able to
    refresh yourself with a sacolé if there's someone selling it there
    (there usually is), and you are likely to see the people jumping
    from [[#pedra-bonita][Pedra Bonita]] on hang gliders (if you are lucky you might even
    see up close someone jumping from Gávea on a wing-suit).

    After the descent you may want to refresh yourself at the small
    waterfall next to the trail (you should have seen the sign during
    the ascent).

**** Alternative trail: the P4

     You can go up Gávea not only through the main trail but also
     through this alternative trail, named /Pico dos Quatro/ and
     shortened as P4. This can a be a less challenging hike if you
     forgo reaching the top and stop at the /Garganta do Céu/, a small
     rocky veranda between two of Gávea's rocky outcrops. It has an
     intimate view of São Conrado, the sea, and the Westernmost parts
     of Zona Sul. If you are up for the challenge, you can continue up
     until the top, but it is a much harder climb than the
     /carrasqueira/ if you have no equipment. You can always hire
     someone to take you there if you really want to, but if you are
     going to Gávea for the first time the main trail is definitely
     amazing enough!

*** Praias selvagens
    :PROPERTIES:
    :CUSTOM_ID: praias-selvagens
    :END:
    This is one of the best hikes you can do in Rio when it's warm
    outside: it takes you away from Zona Sul and the usual touristic
    hotpots, it has beautiful views, and it intercalates hiking with
    refreshing sea baths. It is pretty far from Rio's downtown,
    however; think of it more as a day trip than as a small part of
    your day. You can definitely get there by [[#rio-transport][public transport]], but
    it's likely to take even longer. The best option to go is by car,
    hopefully you or someone you know has a car, or maybe if you are
    renting a car to go to Paraty or Angra dos Reis (which is highly
    recommended) you can rent it one day early to do this hike (or
    maybe you can do the hike and continue the trip from there, which
    should save you some time (because you are already near the
    Western edge of Rio) even if it's likely to be tiring).

    If you do decide to do this hike you may have the impression
    you're in a totally different city from Rio, and while you'd be
    wrong it's a thought that makes sense. The exquisite and mostly
    empty beaches are completely different from other Rio beaches, and
    the landscape looks like a mix of Rio's (the State) beach towns of
    Búzios (to the East of the city of Rio) and Angra dos Reis/Paraty
    (to the West). On a day with a clear view you can see Barra and
    [[#pedra-da-gavea][Pedra da Gávea]] on one direction and Angra dos Reis and Ilha Grande
    on the other, together with the beautiful /Restinga da Marambaia/,
    a protected environmental area stewarded by the military.

*** Pico da Tijuca
    :PROPERTIES:
    :CUSTOM_ID: pico-da-tijuca
    :END:
    Virtually the highest peak of the city at roughly 1020 meters (the
    Pico da Pedra Branca is a few meters higher, but it has a worse
    view), Pico da Tijuca gives you a great view of the Tijuca forest,
    the Guanabara bay, and the other peaks of the Tijuca National
    Park. It can be accessed from the main entrance to Tijuca National
    Park, and is right next to [[#pico-do-papagaio][Pico do Papagaio]] (you could do both
    hikes in the same day if you'd like; if you go up by car until the
    trail head it's not even too tiring).

*** Pico do Papagaio
    :PROPERTIES:
    :CUSTOM_ID: pico-do-papagaio
    :END:
    Pico do Papagaio is one of the highest peaks of the Tijuca
    National Park, and stands between the [[#pico-da-tijuca][Pico da Tijuca]] and Pico do
    Cocanha. Its top is a pretty rocky outcrop you can better
    appreciate from other peaks, and it has at least two stone
    veranda-like ledges in which you can relax and appreciate the
    beautiful view to the Tijuca forest and Barra. If you have a rope
    (and maybe some more climbing gear if you want to be extra safe)
    you can go up the rock in the summit and profit from an even
    better panoramic view.

*** Pico do Perdido
    :PROPERTIES:
    :CUSTOM_ID: pico-do-grajau
    :END:
    This too takes you from the touristic hotspots of the city. Grajaú
    is a pretty neighbourhood near Tijuca. Unlike most of Rio's
    neighbourhoods, it planned, so the streets are mostly straight and
    the layout is simple (but rigid). On top of the charming little
    houses or low buildings towers Pico do Perdido (also called /Pedra
    do Grajaú/), a roughly 400 meter high rocky peak at the edge of
    Tijuca National Park. You can go up from /praça/ (square) Edmundo
    Rêgo to Grajaú State Park, where you can find not only the
    trail-head but also a lot of bouldering practitioners and playing
    children. This trail is still recovering from a fire some ten
    years ago (tropical rain forests are not meant to burn like most of
    Australia's and Western United States' forests, so they take a
    while to recover). Another option is to go through rua Borda do
    Mato to the trail head at rua Marianópolis. This option is more
    heavily forested and boasts a few small waterfalls that can
    refresh you (in the wet season when they have more water you can
    even comfortably bathe in some of them). The potential downside is
    that this way goes almost to the entrance of the Borda do Mato
    favela, so you may worry about safety (it's likely to be OK,
    though). Both options will take you to a small climbing section
    nicknamed /carrasqueirinha/ (after Gávea's /carrasqueira/, which
    is longer and scarier but maybe actually slightly easier after
    all?)

    The view from Pico do Perdido is quite different from most. From
    the back of the summit you can see the mountains and forests of
    Tijuca National Park rising up (there's a stone ledge for you to
    sit down in and bask in the scenery), and from the front you have
    a view of Tijuca, the city center and the closest portions of Zona
    Norte, all in all a pretty urban landscape (that's the concrete
    jungle for you). Still, you can see the mountains rising up behind
    Tijuca too, and Guanabara bay is at its finest (you may even see
    the Serra dos Órgãos up the back of Guanabara bay on a clear day).

*** (Niterói) Pedra do Elefante / Costão de Itacoatiara / Enseada do Bananal
    :PROPERTIES:
    :CUSTOM_ID: pedra-do-elefante
    :END:
    Like [[#praias-selvagens][Praias Selvagens]], think of this as a day trip if you are
    based in Rio. Near Itacoatiara beach, in the edge of Niterói and
    almost in the city of Maricá, you can find the beautiful Pedra do
    Elefante, a fairly high mountain for this region, and one with
    great views of Rio, Niterói and Maricá. The ascent is not too long
    and has an easy climbing part which is a joy to go through. Going
    back down you can either go refresh yourself on the beach (do note
    that Itacoatiara is mostly frequented by surfers because of its
    strong winds and waves; bathers usually go to the right side of
    the beach where a big rock creates a calmer zone where anyone can
    enjoy the waters safely) or go back up to Costão de Itacoatiara, a
    rocky hill which can be easily ascended and is great to watch the
    sunset on. The view from Pedra do Elefante is strictly better than
    that of Costão, so if you are hard-pressed for time you may skip
    the later; similarly, if you'd rather do a lighter hike with an
    almost as good view, Costão de Itacoatiara is a great
    call. Between Pedra do Elefante and Costão de Itacoatiara you have
    the Enseada do Bananal (accessible through the same trail head as
    the Costão), a small bay that almost transports you to another
    dimension, because you can't really see anything except for the
    mountains to your sides and the sea. The Enseada has some climbing
    spots, a small and rocky beach you probably shouldn't enter (the
    currents are strong and the rocks may be dangerous), and pretty
    vegetation.

*** (Petrópolis) Pedra do Bonnet
    :PROPERTIES:
    :CUSTOM_ID: pedra-do-bonnet
    :END:
    This day trip to Petrópolis (which should take you only one and a
    half hours one leg on a lucky day) will take you to the quaint
    neighbourhood of Fazenda Inglesa, which is heavily forested and
    has lots of pretty houses and small hotels. After a few kilometers
    on a narrow road you will get to the trail head, right next to a
    small stream where you can refresh yourself. This is a somewhat
    short hike, so short in fact that you may want to schedule
    something else to do like visiting the Museu Imperial, or maybe
    staying over Petrópolis for a few days and enjoying the city and
    some of its other hikes. Despite being short, the ascent is
    somewhat steep, so take your time and enjoy it, and be careful
    with your knees! When you get to the top you have a few small
    boulders to climb on top of, and a great scenery — on a lucky day
    you should see Guanabara Bay and even Rio (like you can see
    Petrópolis' mountains from Rio on a clear day), and the valleys
    and forests and mountains of that part of Petrópolis. (On an
    unlucky day it will be super foggy and you will see nothing but
    white.)

*** Praia da Joatinga
    One of Rio's smallest beaches, it can be accessed by car or bus
    (you must enter a very fancy private gated community, but they
    have to let you in since the beach itself is public). The seawater
    quality there is not always great, do check it if you want to
    bathe, although there will always be people there bathing and none
    die as far as the writer knows.

    The beach itself is very unique, since you have to go through a
    rock face to reach it (nothing difficult but be careful of
    slipping — don't wear wet Havaianas to go down), and it is
    enclosed by large rock walls on all sides but the sea side (this
    also means that the sun may set there earlier, depending on the
    season).

*** Jardim Botânico
    The national botanic garden in the eponymous neighbourhood of
    Jardim Botânico has plants from all over the world, and strolling
    through it is a great outdoors activity. You'll see not only the
    plants and flowers and trees, but also children, seniors and
    couples taking wedding pictures.

    Jardim Botânico is not expensive, but it is not free either. A
    nearby alternative is Parque Lage, which has the usual native
    vegetation of Rio, is also a joy to stroll through, and hosts the
    Visual Arts School in the mansion built by the Enrique Lage that
    names the park (you may recognize it from 2000's video clips like
    Snoop Dog's “Beautiful” and Black Eyed Peas's “Don't lie”). From
    there there's also a trail head that takes you up to Corcovado
    mountain, but to reach the summit (where you find Cristo Redentor)
    you have to pay for a ticket (the view is exquisite, so it may be
    worth it). Do note that this trail is notably dangerous because it
    is mostly frequented by tourists (most other trails in Rio are
    safe (as much as anything is safe in Rio), with maybe the
    exception of the beautiful ascent to Pedra dos Dois Irmãos).
** Culture

*** Museu Nacional de Belas Artes (MNBA)
    :PROPERTIES:
    :CUSTOM_ID: mnba
    :END:

    A traditional art museum in Cinelândia square, close to other
    places like the [[#theatro-municipal][Theatro Municipal]] and the [[#biblioteca-nacional][Biblioteca Nacional]]. It
    has mostly Western and Western-inspired art, and can be an
    opportunity to know more about Brazilian art (specially when it
    starts to become more different from European art with the
    Modernists of the 1920s and 1930s).

*** Biblioteca Nacional
    :PROPERTIES:
    :CUSTOM_ID: biblioteca-nacional
    :END:
    The equivalent of the US Congress Library or the British Library,
    all books published in Brazil must send a copy to the Biblioteca
    Nacional. It is a building with a Neoclassical architecture that
    fits well with its neighbours the [[#mnba][Museu Nacional de Belas Artes]]
    and the [[#theatro-municipal][Theatro Municipal]]. Its collection originates from the time
    Rio was the capital of the Portuguese empire, and holds several
    historical documents of interest.

*** Real Gabinete Português de Leitura
    :PROPERTIES:
    :CUSTOM_ID: real-gabinete-portugues-de-leitura
    :END:
    Most likely the most architecturally beautiful library in Rio, and
    sits right next to several used book stores (/sebos/). Definitely
    worth a visit, even if there's not much more to do than look at
    the pretty book shelves and old books (unless you go there to read,
    of course).

*** Theatro Municipal
    :PROPERTIES:
    :CUSTOM_ID: theatro-municipal
    :END:
    Rio's main opera house. You can almost always grab a concert or
    opera for cheap (specially the Sunday morning concerts for
    R$1.00). Sometimes there are quite extraordinary events available,
    like Paco de Lucía and Keith Jarret concerts. If you go to São
    Paulo you might want to decide between going to their Theatro
    Municipal instead — I'd pick based on what events are available at
    each.

*** Palácio Gustavo Capanema
    :PROPERTIES:
    :CUSTOM_ID: palacio-gustavo-capanema
    :END:
    A pearl of Brazilian Modernist architecture. There's usually some
    cultural exhibit available, but just going in to appreciate the
    design is reward enough.

*** Centro Cultural Banco do Brasil (CCBB)
    :PROPERTIES:
    :CUSTOM_ID: ccbb
    :END:
    This cultural center lies at an old branch of Banco do Brasil. It
    usually has some of the best exhibits in the city (and in Brazil),
    bringing in the best art and culture from abroad (while sometimes
    showing something originally Brazilian). Despite it not having a
    permanent collection of great note (there are some artifacts
    related to Brazilian monetary history, maybe more), it has
    attracted great lines that go around its corner, with some
    exhibits attracting millions of visitors (a large chunk of the
    city's population of six million).

    CCBB's neighbour the Centro Cultural dos Correios is its poorer
    sibling, but it nevertheless sometimes holds interesting exhibits,
    and it usually doesn't have a queue like CCBB often has (specially
    on rainy weekends and late afternoons after people leave work).

*** Mosteiro de São Bento
    :PROPERTIES:
    :CUSTOM_ID: mosteiro-de-sao-bento
    :END:
    Lying atop a hill in Rio's city center, this exquisite church with
    a simple façade has a golden Baroque interior. It is one of the
    calmest places in Rio's city center, the best place for a moment
    of relaxation in that area.

*** Museu do Amanhã
    :PROPERTIES:
    :CUSTOM_ID: museu-do-amanha
    :END:
    A shiny new building hosting a museum about humanity's future,
    focusing on the threat of climate change. The museum has a very
    interesting architecture that differs from most of Rio's other
    buildings, and crowns the revitalization of Rio's port district.

    Make sure to visit the murals on the promenade to the side of the
    Mauá Square where the museum lies, and maybe check the exhibits
    available at the Rio Art Museum (Museu de Arte do Rio (MAR))
    nearby — they may be worthwhile. You can also go to the top of MAR
    for a good view of that corner of Rio's city center and of
    Guanabara Bay.

*** Convento de Santo Antônio
    :PROPERTIES:
    :CUSTOM_ID: convento-de-santo-antonio
    :END:
    Lying atop a hill on Rio's city center, the convent has a nice
    view of the Largo da Carioca below (you could watch the people
    come and go for hours if you were so inclined), and a beautiful
    church inside.

    Nearby you will find the the very different-looking Cathedral of
    Rio, which looks like a cement Mayan pyramid (but is quite pretty
    from the inside, with the lights coming in through the stained
    glass), and the also incredibly ugly-looking main building of the
    national oil company Petrobras (it's the building that looks like
    a partially hollowed out cube).
