name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox elpa-htmlize --no --yes

      - name: Build the site
        run: ./make-site.sh

      - name: Publish generated content to GitHub Pages
        uses: odanoburu/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public